#ddev-generated

http:
  routers:
    
    
    ootstra-phpmyadmin-80-http:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-phpmyadmin-80-http"
      tls: false
      entrypoints:
        - http-8036
    
    
    
    ootstra-web-80-http:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-web-80-http"
      tls: false
      entrypoints:
        - http-80
    
    
    ootstra-web-8025-http:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-web-8025-http"
      tls: false
      entrypoints:
        - http-8025
    
    
    ootstra-web-3000-http:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-web-3000-http"
      tls: false
      entrypoints:
        - http-3000
    
    
    
    
    
    
    ootstra-phpmyadmin-80-https:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-phpmyadmin-80-https"
      
      tls: true
      
      entrypoints:
        - http-8037
    
    
    
    
    
    ootstra-web-80-https:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-web-80-https"
      
      tls: true
      
      entrypoints:
        - http-443
    
    
    ootstra-web-8025-https:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-web-8025-https"
      
      tls: true
      
      entrypoints:
        - http-8026
    
    
    ootstra-web-3000-https:
      
      rule: HostRegexp(`ootstra.ddev.site`)
      
      middlewares:
        - autodetect
      service: "ootstra-web-3000-https"
      
      tls: true
      
      entrypoints:
        - http-3000
    
    

  # autodetect won't be needed in Traefik 3 https://github.com/traefik/traefik/pull/9546
  middlewares:
    autodetect:
      contentType:
        autoDetect: false

  services:
    
    ootstra-phpmyadmin-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-phpmyadmin:80
    
    ootstra-phpmyadmin-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-phpmyadmin:80
    
    ootstra-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-web:80
    
    ootstra-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-web:8025
    
    ootstra-web-3000-http:
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-web:3000
    
    ootstra-web-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-web:80
    
    ootstra-web-8025-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-web:8025
    
    ootstra-web-3000-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-ootstra-web:3000
    


tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/ootstra.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/ootstra.key

